language: python
python:
    - '3.6'
    - '3.7'
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y netcdf-bin
install:
    - pip install --upgrade pip pytest coverage codecov six pytest-cov
    - pip install .[dev]
script: python -m pytest
after_success:
    - codecov
