language: python
python:
    - '2.6'
    - '2.7'
    - '3.5'
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y netcdf-bin
install:
    - pip install --upgrade pip pytest coverage codecov
    - pip install .[dev]
script:
    - coverage run --source addmeta -m py.test
after_success:
    - codecov
