{% set name = "addmeta" %}
{% set version = "0.2.2+17.g9fa3419.dirty" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: file:///Users/davide/access-nri/projects/addmeta/dist/addmeta-0.2.2+17.g9fa3419.dirty.tar.gz
  sha256: f4b0074de8ea664197e51d0f955858c87a585bb0d094a742f79169a0dc8c39a0

build:
  entry_points:
    - addmeta = addmeta.cli:main_argv
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - versioneer
    - pip
  run:
    - python >=3.9
    - netcdf4
    - pyyaml

test:
  imports:
    - addmeta
  commands:
    - pip check
    - addmeta --help
  requires:
    - pip

about:
  summary: Add meta data to netCDF files.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - atteggiani
