{% set version = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True).get('version') %}
{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set project = pyproject.get('project') %}
{% set requires_python = pyproject.get('requires-python', "") %}
{% set test_dependencies = project.get('optional-dependencies', {}).get('dev', []) %}
{% set build_dependencies = pyproject.get('build-system', {}).get('requires', []) %}
{% set is_noarch = pyproject.get('tool', {}).get('wheel', {}).get('universal', "") %}

package:
    name: {{ project.get('name') }}
    version: "{{ version }}"

build:
    number: 0
    {% if is_noarch %}
    noarch: python
    {% endif %}
    script:
      - {{ PYTHON }} -m pip install . --no-deps -vv
    entry_points:
        {% for name, script in project.get('scripts', {}).items() %}
        - {{ name }} = {{ script }}
        {% endfor %}

source:
    # TARBALL_PATH env variable is set in the CD.yml workflow
    url: "{{ environ.get('TARBALL_PATH') }}"

requirements:
    host:
        - python {{ requires_python }}
        - pip
        {% for dep in build_dependencies %}
        - "{{ dep }}"
        {% endfor %}
    run:
        {% for dep in project.get('dependencies') %}
        - "{{ dep }}"
        {% endfor %}

test:
    {% if test_dependencies %}
    requires:
        {% for dep in test_dependencies %}
        - "{{ dep }}"
        {% endfor %}
    {% endif %}
    commands:
        {% for name, script in project.get('scripts').items() %}
        - {{ name }} --help
        {% endfor %}

about:
    home: {{ project.get('urls', {}).get('Repository', "") }}
    license: {{ project.get('license', "") }}
    license_file: {{ project.get('license-files', [""])[0] }}
    summary: {{ project.get('description') }}

