package:
    name: addmeta
    version: {{ GIT_DESCRIBE_TAG }}

build:
    number: {{ GIT_DESCRIBE_NUMBER }}
    string: {{ GIT_BUILD_STR }}

source:
    git_url: ../

build:
    script: python setup.py install

requirements:
    build:
        - python
        - pbr
    run:
        - python
        - pyyaml
        - netcdf4
        - xarray
test:
    source_files:
        - setup.cfg
        - test
    requires:
        - pytest
        - pytest-cov
    commands:
        - python -m pytest

about:
    home: https://github.com/coecms/addmeta
    license: Apache 2.0
    license_file: LICENSE
