{% set version = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True).get('version') %}
{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set project = pyproject.get('project') %}
{% set requires_python = pyproject.get('requires-python', {}) %}
{% set test_dependencies = project.get('optional_dependencies', {}).get('dev', []) %}
{% set build_dependencies = pyproject.get('build-system', {}).get('requires', []) %}

package:
    name: {{ project.get('name') }}
    version: "{{ version }}"

build:
    number: 0
    noarch: python
    script: "python3 -m pip install . --no-deps -vv"
    entry_points:
        {% for name, script in project.get('scripts').items() %}
        - {{ name }} = {{ script }}
        {% endfor %}

source:
    # CD sets TARBALL_PATH env variable
    path: {{ environ.get('TARBALL_PATH') }}

requirements:
    host:
        - python {% requires_python | default("", boolean=True) %}
        - pip
        {% for dep in build_dependencies %}
        - {{ dep }}
        {% endfor %}
    run:
        {% for dep in project.get('dependencies') %}
        - {{ dep }}
        {% endfor %}

test:
    {% if test_dependencies %}
    requires:
        {% for dep in optional_dependencies %}
        - {{ dep }}
        {% endfor %}
    {% endif %}
    commands:
    {% for name, script in project.get('scripts').items() %}
        - {{ name }} --help
    {% endfor %}
    $PYTHON -m pytest

about:
    home: {{ project.get('urls').get('Repository') }}
    license: Apache Software
    license_file: LICENSE
    summary: {{ project.get('description') }}

