global:
   organisation : "ARC Centre of Excellence for Climate System Science / Climate Change Research Centre"
   Conventions : "CF-1.6, ACDD-1.3"
   license : "http://creativecommons.org/licenses/by-nc-nd/4.0/"
