name: CD

on:
  push:
    tags:
      - '**'
  pull_request:
env:
  PYTHON_PACKAGE_ARTIFACT: python-package
  CONDA_PACKAGE_ARTIFACT: conda-package

jobs:
  get-package-name:
    name: Get package name
    runs-on: ubuntu-latest
    outputs:
      package-name: ${{ steps.get-package-name.outputs.package-name }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      
      - name: Get name
        id: get-package-name
        run: |
          echo "package-name=$(yq '.project.name' pyproject.toml)" >> $GITHUB_OUTPUT
  
  publish_python_package:
    needs: get-package-name
    uses: access-nri/actions/.github/workflows/publish-python-package.yml@davide/publish-python-package
    secrets: inherit
    permissions:
      actions: write

  list-artifact:
    name: List artifact
    runs-on: ubuntu-latest
    needs: publish_python_package
    steps:
      - name: Test
        run: echo '${{ needs.publish_python_package.outputs.artifact-name }}'

      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
            name: ${{ needs.publish_python_package.outputs.artifact-name }}
            path: downloaded-artifacts
        
      - name: List artifacts
        run: ls -la downloaded-artifacts