name: Pytests
on:
  push:
    branches:
      - master
  pull_request:
  workflow_call:
jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        python-version: ["3.9"]
    steps:
      - run: sudo apt-get install -y netcdf-bin

      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: pip install .[dev]

      - name: Run tests
        run: python -m pytest

  codecov:
    needs: pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install codecov
        run: pip install codecov

      - name: Upload coverage to codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: codecov
